- name: Create ec2 stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks: 
    
    - name: Import VPC setup variables
      include_vars: vars/output_vars

    - name: Import AMI setup variables
      include_vars: vars/ec2_setup

    - name: Import VPC setup
      include_vars: vars/vpc_setup

    - name: Create PROJECT ec2 key
      ec2_key:
        name: ec2-project-key
        region: "{{region}}"
      register: key_pair_out
  
    - name: Save key in a file
      copy: 
        content: "key_pair_out.key.private_key"
        dest: "./ec2-project-key.pem"
        mode: 0600
      when: key_pair_out.changed

    - name: Create SG for ELB
      ec2_group:
        name: Project_ELB-SG
        description: Allow port 80 from anywhere and all ports within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: ProjectELBSG_out

    - name: Create SG for ec2 stack
      ec2_group:
        name: Project_ec2_SG
        description: Allow port 22 from everywhere and all ports within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ProjectELBSG_out.group_id}}"
          
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionSGid}}"
      register:  Project_ec2_SG_out

    - name: Update ec2 SG to allow all traffic in this SG. For host internal communication
      ec2_group:
        name: Project_ec2_SG
        description: Allow all traffic internally for all ec2 hosts
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{Project_ec2_SG_out.group_id}}"

