- name: Create ec2 stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks: 
    
    - name: Import VPC setup variables
      include_vars: vars/output_vars

    - name: Import AMI setup variables
      include_vars: vars/ec2_setup

    - name: Import VPC setup
      include_vars: vars/vpc_setup

    - name: Create PROJECT ec2 key
      ec2_key:
        name: ec2-project-key
        region: "{{region}}"
      register: key_pair_out
  
    - name: Save key in a file
      copy: 
        content: "key_pair_out.key.private_key"
        dest: "./ec2-project-key.pem"
        mode: 0600
      when: key_pair_out.changed

    - name: Create SG for ELB
      ec2_group:
        name: Project_ELB-SG
        description: Allow port 80 from anywhere and all ports within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: ProjectELBSG_out

    - name: Create SG for ec2 stack
      ec2_group:
        name: Project_ec2_SG
        description: Allow port 22 from everywhere and all ports within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ProjectELBSG_out.group_id}}"
          
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionSGid}}"
      register:  Project_ec2_SG_out

    - name: Update ec2 SG to allow all traffic in this SG. For host internal communication
      ec2_group:
        name: Project_ec2_SG
        description: Allow all traffic internally for all ec2 hosts
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{Project_ec2_SG_out.group_id}}"


    - name: Create NGINX web01
      ec2_instance:
        name: "web01"
        region: "{{region}}"
        key_name: "ec2-project-key"
        instance_type: t2.micro
        image: "{{nginx_ami}}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "web01"
          Project: Project
          Owner: Tony
        exact_count: 1
        security_group: "{{Project_ec2_SG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: web01_out

    - name: Create Tomcat app01
      ec2_instance:
        name: "app01"
        region: "{{region}}"
        key_name: "ec2-project-key"
        instance_type: t2.micro
        image: "{{tomcat_ami}}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "app01"
          Project: Project
          Owner: Tony
        exact_count: 1
        security_group: "{{Project_ec2_SG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: app01_out

    - name: Create Memcache mc01
      ec2_instance:
        name: "mc01"
        region: "{{region}}"
        key_name: "ec2-project-key"
        instance_type: t2.micro
        image: "{{memcache_ami}}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "mc01"
          Project: Project
          Owner: Tony
        exact_count: 1
        security_group: "{{Project_ec2_SG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: mc01_out

    - name: Create RabbitMQ rmq01
      ec2_instance:
        name: "rmq01"
        region: "{{region}}"
        key_name: "ec2-project-key"
        instance_type: t2.micro
        image: "{{rmq_ami}}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "rmq01"
          Project: Project
          Owner: Tony
        exact_count: 1
        security_group: "{{Project_ec2_SG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: rmq01_out

    - name: Create MySQL db01
      ec2_instance:
        name: "db01"
        region: "{{region}}"
        key_name: "ec2-project-key"
        instance_type: t2.micro
        image: "{{mysql_ami}}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "db01"
          Project: Project
          Owner: Tony
        exact_count: 1
        security_group: "{{Project_ec2_SG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: db01_out

    - debug:
        var: db01_out

        