- name: Generate artifact, copy artifact & sql file to file directories
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install jdk, maven, git
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
      - git
      - openjdk-8-jdk
      - maven

    - name: Clone sourcecode from github
      git:
        repo: 'https://github.com/GuzAnton/vprofile-source-code.git'
        dest: ./vprofile-source-code
        version: vp-rem
      register: git_status
    
    - name: mvn install command to build artifact
      command: "mvn install"
      args:
        chdir: vprofile-source-code
      when: git_status.changed
      register: mvn_info

    - name: Copy artifacts to files directory
      copy:
        src: "{{item}}"
        dest: files/ROOT.war
      with_fileglob: vprofile-source-code/target/*.war

    - name: Copy SQL file to files directory
      copy:
        src: vprofile-source-code/src/main/resources/db_backup.sql
        dest: files/db_backup.sql