- name: Setup MYSQL with "accounts" db and remote login
  hosts: dbsrvgrp
  gather_facts: False
  tasks:

    - name: Installing MYSQL server and dependencies
      package:
        name: "{{item}}"
        state: present
        update_cache: True
        cache_valid_time: 86400
      loop:
        - mysql-server
        - mysql-client
        - python-mysqldb
        - python3-mysqldb
        - libmysqlclient-dev
      ignore_errors: True
      tags:
        - package

    - name: Start and enable MYSQL service_facts
      service:
        name: mysql
        state: started
        enabled: yes
      tags:
        - svc

    - name: Create MYSQL user
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: Create accounts DB
      mysql_db:
        name: "{{dbname}}"
        state: present

    - name: Enable remote login to mysql svc
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.conf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - Restart mysql
      tags:
        - conf

  handlers:
  - name: Restart mysql
    service:
      name: mysql
      state: restarted
