- name: Deploy SQL file on db
  hosts: dbsrvgrp
  gather_facts: no
  tasks:

    - name: Copy SQL to dbserver
      copy:
        src: files/db_backup.sql
        dest: /tmp/db_backup.sql
      tags:
        - deploy

    - name: Restore DB
      mysql_db:
        name: "{{dbname}}"
        login_user: "{{dbuser}}"
        login_password: "{{dbpass}}"
        state: import
        target: /tmp/db_backup.sql
      notify:
        - restart mysql
      tags:
        - deploy

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
