- name: Install & Setup RabbitMQ with user
  hosts: rmqsrvgrp
  gather_facts: no
  tasks:
   
    - name: Copy Erlang & RabbitMQ installation script
      copy:
        src: group_vars/install_rabbitmq.sh
        dest: /tmp/install_rabbitmq.sh
        mode: u+x  # Set the executable permission
      become: yes
      tags:
        - rabbitmq
    
    - name: Run Erlang & RabbitMQ installation script
      shell: /tmp/install_rabbitmq.sh
      become: yes
      tags:
        - rabbitmq


    - name: Add RabbitMQ user
      rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - Restart RMQ

    - name: Enable RabbitMQ management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - Restart RMQ

  handlers:
    - name: Restart RMQ
      service:
        name: rabbitmq-server
        state: restarted
