- name: Install and enable RabbitMQ
  gather_facts: no
  hosts: rmqsrvgrp
  tasks:
    - name: Add erlang Repo
      apt_key: 
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        state: present
 
    - apt_repository:
        repo: deb https://packages.erlang-solutions.com/ubuntu bionic contrib
        state: present
 
    - name: Install Erlang
      apt:
        name: erlang
        state: present