- name: Install & Setup RabbitMQ with user
  hosts: rmqsrvgrp
  gather_facts: no
  tasks:
    - name: Copy Erlang installation script
      copy:
        src: group_vars/install_erlang.sh
        dest: /tmp/install_erlang.sh
        mode: u+x  # Set the executable permission
      become: yes
      tags:
        - erlang
    
    - name: Run Erlang installation script
      shell: /tmp/install_erlang.sh
      become: yes
      tags:
        - erlang

    - name: Configure RabbitMQ
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - Restart RMQ

    - name: Add RabbitMQ user
      rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - Restart RMQ

    - name: Enable RabbitMQ management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - Restart RMQ

  handlers:
    - name: Restart RMQ
      service:
        name: rabbitmq-server
        state: restarted
