- name: Install & Setup RabbitMQ with user
  hosts: rmqsrvgrp
  gather_facts: no
  tasks:
    - name: Add Erlang Solutions Repository Key
      apt_key:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        state: present

    - name: Add Erlang Solutions Repository
      apt_repository:
        repo: deb https://packages.erlang-solutions.com/ubuntu bionic contrib
        state: present

    - name: Update Package Cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Install Erlang and its dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - erlang
        - erlang-common-test
        - erlang-debugger
        - erlang-et
        - erlang-megaco
        - erlang-observer
        - erlang-reltool
        - erlang-test-server
        - erlang-wx
        - erlang-ic-java
        - erlang-src
        - erlang-examples
      register: erlang_install_result
      ignore_errors: yes

    - name: Retry installing Erlang and its dependencies (if failed) with recommended options
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        install_recommends: yes
      loop: "{{ erlang_install_result.results | selectattr('failed') | map(attribute='item') | list }}"
      when: erlang_install_result.results | selectattr('failed') | map(attribute='item') | list | length > 0

    - name: Fail if Erlang installation is still unsuccessful
      fail:
        msg: "Failed to install Erlang and its dependencies"
      when: erlang_install_result | failed

    - name: Install RabbitMQ server
      apt:
        name: rabbitmq-server
        state: present
        update_cache: yes

    - name: Start & Enable RabbitMQ service
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Configure RabbitMQ
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - Restart RMQ

    - name: Add RabbitMQ user
      rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - Restart RMQ

    - name: Enable RabbitMQ management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - Restart RMQ

  handlers:
    - name: Restart RMQ
      service:
        name: rabbitmq-server
        state: restarted
