---
- name: Configure RabbitMQ on Ubuntu 20.04 LTS
  hosts: rmqsrvgrp
  gather_facts: no
  become: yes
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Install curl and gnupg packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - gnupg

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Add RabbitMQ GPG key
      shell: "curl -1sLf 'https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA' | sudo gpg --dearmor | sudo tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null"
      args:
        executable: /bin/bash

    - name: Add Erlang GPG key
      shell: "curl -1sLf 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf77f1eda57ebb1cc' | sudo gpg --dearmor | sudo tee /usr/share/keyrings/net.launchpad.ppa.rabbitmq.erlang.gpg > /dev/null"
      args:
        executable: /bin/bash

    - name: Add RabbitMQ repository
      copy:
        content: |
          # Source repository definition example.

          ## Provides modern Erlang/OTP releases
          ##
          ## "focal" as distribution name should work for any reasonably recent Ubuntu or Debian release.
          ## See the release to distribution mapping table in RabbitMQ doc guides to learn more.
          deb [signed-by=/usr/share/keyrings/net.launchpad.ppa.rabbitmq.erlang.gpg] http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu focal main
          deb-src [signed-by=/usr/share/keyrings/net.launchpad.ppa.rabbitmq.erlang.gpg] http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu focal main

          ## Provides RabbitMQ
          ##
          ## "focal" as distribution name should work for any reasonably recent Ubuntu or Debian release.
          ## See the release to distribution mapping table in RabbitMQ doc guides to learn more.
          deb [signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ focal main
          deb-src [signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ focal main
        dest: /etc/apt/sources.list.d/rabbitmq.list

    - name: Update apt cache after adding repository
      apt:
        update_cache: yes

    - name: Install Erlang packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - erlang-base
        - erlang-asn1
        - erlang-crypto
        - erlang-eldap
        - erlang-ftp
        - erlang-inets
        - erlang-mnesia
        - erlang-os-mon
        - erlang-parsetools
        - erlang-public-key
        - erlang-runtime-tools
        - erlang-snmp
        - erlang-ssl
        - erlang-syntax-tools
        - erlang-tftp
        - erlang-tools
        - erlang-xmerl

    - name: Install RabbitMQ server and its dependencies
      apt:
        name: rabbitmq-server
        state: present
        update_cache: yes
        force_apt_get: yes
